# Site settings
title: LinkedPipes
email: klimek@opendata.cz
author: 
    name: "Jakub Klímek"
    twitter: jakub_klimek

description: > # this means to ignore newlines until "baseurl:"
  LinkedPipes is a suite of open-source software for Linked Data
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://linkedpipes.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->

gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
